package dao;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import dao.mappers.IMapResultSetToEntity;
import dao.uow.IUnitOfWork;
import domain.Permission;

public class PermissionRepository extends RepositoryBase<Permission> implements
		IPermissionRepository {

	public PermissionRepository(Connection connection,
			IMapResultSetToEntity<Permission> mapper, IUnitOfWork uow) {
		super(connection, mapper, uow);
	}

	@Override
	protected void setUpdateQuery(Permission p) throws SQLException {
		update.setString(1, p.getName());
		update.setInt(2, p.getId());
	}

	@Override
	protected void setInsertQuery(Permission p) throws SQLException {
		insert.setString(1, p.getName());
	}

	@Override
	protected String tableName() {
		return "t_sys_permissions";
	}

	@Override
	protected String createTableSql() {
		return "CREATE TABLE t_sys_permissions("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "name VARCHAR(50)" + ")";
	}

	@Override
	protected String insertSql() {
		return "INSERT INTO t_sys_permissions(name) VALUES (?)";
	}

	@Override
	protected String updateSql() {
		return "UPDATE t_sys_permissions SET name = ? WHERE id = ?";
	}

	public List<Permission> withName(String name) {
		// TODO Auto-generated method stub
		return null;
	}
}
