package dao;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import dao.mappers.IMapResultSetToEntity;
import dao.uow.IUnitOfWork;
import domain.Person;

public class PersonRepository extends RepositoryBase<Person> implements
		IPersonRepository {

	public PersonRepository(Connection connection,
			IMapResultSetToEntity<Person> mapper, IUnitOfWork uow) {
		super(connection, mapper, uow);
	}

	public void setUpdateQuery(Person p) throws SQLException {
		update.setString(1, p.getLogin());
		update.setString(2, p.getPassword());
		update.setInt(3, p.getId());
	}

	public void setInsertQuery(Person p) throws SQLException {
		insert.setString(1, p.getLogin());
		insert.setString(2, p.getPassword());
	}

	@Override
	protected String tableName() {
		return "t_sys_users";
	}

	protected String createTableSql() {
		return "CREATE TABLE t_sys_users("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "login VARCHAR(20)," + "password VARCHAR(50)" 
				+ ")";
	}

	protected String insertSql() {
		return "INSERT INTO t_sys_users(login, password) VALUES (?,?)";
	}

	protected String updateSql() {
		return "UPDATE t_sys_users SET login = ?, password = ? WHERE id = ?";
	}

	public List<Person> withLogin(String login) {
		return null;
	}
}
