package dao;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import dao.mappers.IMapResultSetToEntity;
import dao.uow.IUnitOfWork;
import domain.Role;

public class RoleRepository extends RepositoryBase<Role>
	implements IRoleRepository{

	public RoleRepository(Connection connection,
			IMapResultSetToEntity<Role> mapper, 
			IUnitOfWork uow) {
		super(connection, mapper, uow);
	}

	public List<Role> withName(String name) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	protected void setUpdateQuery(Role p) throws SQLException {
		update.setString(1, p.getRoleName());
		update.setInt(2, p.getId());
	}

	@Override
	protected void setInsertQuery(Role p) throws SQLException {
		insert.setString(1, p.getRoleName());
	}

	@Override
	protected String tableName() {
		return "t_sys_roles";
	}

	@Override
	protected String createTableSql() {
		return "CREATE TABLE t_sys_roles("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "roleName VARCHAR(50)"
				+ ")";
	}

	@Override
	protected String insertSql() {
		return "INSERT INTO t_sys_roles(roleName) VALUES (?)";
	}

	@Override
	protected String updateSql() {
		return "UPDATE t_sys_roles SET roleName = ? WHERE id = ?";
	}
}
